### PR TITLE
Add /api prefix for all endpoints

### PR DESCRIPTION
**Pull request by lenguyenthanh**
As We already have breaking changes

### CODE REVIEW

**Comment by ornicar** [comment]
What for? Will there be non `/api` endpoints?

**Comment by lenguyenthanh** [comment]
there is an optional swagger open API routes: `/docs`: https://github.com/lichess-org/lila-search/blob/aeba424257b50f3c5b92887cc271c7cac1bdceb5/modules/app/src/main/scala/http.routes.scala#L24.

mm, I need to make it a `def` instead of `val`.

**Comment by ornicar** [comment]
Consistency with the lichess API endpoints? But this is not a public API.

**Comment by lenguyenthanh** [comment]
I mean it's a convention to put all endpoints under `/api`, so no harm doing this.

**Pull request merged**
